In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('data/frog_tongue_adhesion.csv', comment='#')

In [4]:
df.head()

,date,ID,trial number,impact force (mN),impact time (ms),impact force / body weight,adhesive force (mN),time frog pulls on target (ms),adhesive force / body weight,adhesive impulse (N-s),total contact area (mm2),contact area without mucus (mm2),contact area with mucus / contact area without mucus,contact pressure (Pa),adhesive strength (Pa)
0,2013_02_26,I,3,1205,46,1.95,-785,884,1.27,-0.290,387,70,0.82,3117,-2030
1,2013_02_26,I,4,2527,44,4.08,-983,248,1.59,-0.181,101,94,0.07,24923,-9695
2,2013_03_01,I,1,1745,34,2.82,-850,211,1.37,-0.157,83,79,0.05,21020,-10239
3,2013_03_01,I,2,1556,41,2.51,-455,1025,0.74,-0.170,330,158,0.52,4718,-1381
4,2013_03_01,I,3,493,36,0.80,-974,499,1.57,-0.423,245,216,0.12,2012,-3975

In [5]:
df.loc[abs(df['adhesive strength (Pa)'])>2000,'impact time (ms)']

0      46
1      44
2      34
4      36
7      46
8      50
11     48
13     31
14     38
17     60
19     40
23     59
24     33
25     43
27     31
29     42
31     57
33     21
35     29
37     31
38     15
39     42
42    105
44     29
45     16
47     31
49     32
50     30
51     16
52     27
53     30
54     35
55     39
57     34
59     34
60     26
61     20
62     55
65     33
66     74
67     26
68     27
69     33
71      6
73     31
74     34
75     38
78     33
Name: impact time (ms), dtype: int64

In [6]:
df.loc[df['ID']=='II',['impact force (mN)', 'adhesive force (mN)']]

    impact force (mN)  adhesive force (mN)
20               1612                 -655
21                605                 -292
22                327                 -246
23                946                 -245
24                541                 -553
25               1539                 -664
26                529                 -261
27                628                 -691
28               1453                  -92
29                297                 -566
30                703                 -223
31                269                 -512
32                751                 -227
33                245                 -573
34               1182                 -522
35                515                 -599
36                435                 -364
37                383                 -469
38                457                 -844
39                730                 -648

In [7]:
df.loc[(df['ID'] == 'III') | (df['ID'] =='IV'),['ID','adhesive force (mN)', 'time frog pulls on target (ms)']]

     ID  adhesive force (mN)  time frog pulls on target (ms)
40  III                  -94                             683
41  III                 -163                             245
42  III                 -172                             619
43  III                 -225                            1823
44  III                 -301                             918
45  III                  -93                            1351
46  III                 -131                            1790
47  III                 -289                            1006
48  III                 -104                             883
49  III                 -229                            1218
50  III                 -259                             910
51  III                 -231                             550
52  III                 -267                            2081
53  III                 -178                             376
54  III                 -123                             289
55  III                 -151                             607
56  III                 -127                            2932
57  III                 -372                             680
58  III                 -236                             685
59  III                 -390                            1308
60   IV                 -456                             462
61   IV                 -193                             250
62   IV                 -236                             743
63   IV                 -225                             844
64   IV                 -217                             728
65   IV                 -161                             472
66   IV                 -139                             959
67   IV                 -264                             844
68   IV                 -342                            1515
69   IV                 -231                             279
70   IV                 -209                            1427
71   IV                 -292                            2874
72   IV                 -339                            4251
73   IV                 -371                             626
74   IV                 -331                            1254
75   IV                 -302                             986
76   IV                 -216                            1627
77   IV                 -163                            2021
78   IV                 -367                            1366
79   IV                 -218                            1269

In [8]:
df.head(
)

,date,ID,trial number,impact force (mN),impact time (ms),impact force / body weight,adhesive force (mN),time frog pulls on target (ms),adhesive force / body weight,adhesive impulse (N-s),total contact area (mm2),contact area without mucus (mm2),contact area with mucus / contact area without mucus,contact pressure (Pa),adhesive strength (Pa)
0,2013_02_26,I,3,1205,46,1.95,-785,884,1.27,-0.290,387,70,0.82,3117,-2030
1,2013_02_26,I,4,2527,44,4.08,-983,248,1.59,-0.181,101,94,0.07,24923,-9695
2,2013_03_01,I,1,1745,34,2.82,-850,211,1.37,-0.157,83,79,0.05,21020,-10239
3,2013_03_01,I,2,1556,41,2.51,-455,1025,0.74,-0.170,330,158,0.52,4718,-1381
4,2013_03_01,I,3,493,36,0.80,-974,499,1.57,-0.423,245,216,0.12,2012,-3975

In [9]:
df.groupby('ID')['impact force (mN)'].agg(['std']).reset_index()

    ID         std
0    I  630.207952
1   II  424.573256
2  III  124.273849
3   IV  234.864328

In [10]:
def coeff_of_var(data):
    return np.mean(data)/np.std(data)
# cols = df.columns[(df.columns == 'impact force (mN)') ]
df.groupby('ID')['impact force (mN)'].agg(coeff_of_var).reset_index()

    ID  impact force (mN)
0    I           2.491165
1   II           1.709306
2  III           4.541508
3   IV           1.830791

In [11]:
df.groupby('ID')[['impact force (mN)', 'adhesive force (mN)']].agg(coeff_of_var).reset_index()

    ID  impact force (mN)  adhesive force (mN)
0    I           2.491165            -4.041459
1   II           1.709306            -2.327197
2  III           4.541508            -2.407117
3   IV           1.830791            -3.246305

In [12]:
df.groupby('ID')[['impact force (mN)', 'adhesive force (mN)']].agg(['mean','median','std',coeff_of_var]).reset_index()

    ID impact force (mN)                                  adhesive force (mN)  \
                    mean  median         std coeff_of_var                mean
0    I           1530.20  1550.5  630.207952     2.491165             -658.40
1   II            707.35   573.0  424.573256     1.709306             -462.30
2  III            550.10   544.0  124.273849     4.541508             -206.75
3   IV            419.10   460.5  234.864328     1.830791             -263.60


  median         std coeff_of_var
0 -664.5  167.143619    -4.041459
1 -517.0  203.811600    -2.327197
2 -201.5   88.122448    -2.407117
3 -233.5   83.309442    -3.246305

In [17]:
ll = df.groupby('ID')[['impact force (mN)', 'adhesive force (mN)']].agg(['mean','median','std',coeff_of_var]).reset_index()
df2 = pd.melt(ll, value_name='Value', var_name=['Force', 'Method'], id_vars='ID')
df2

     ID                Force        Method        Value
0     I    impact force (mN)          mean  1530.200000
1    II    impact force (mN)          mean   707.350000
2   III    impact force (mN)          mean   550.100000
3    IV    impact force (mN)          mean   419.100000
4     I    impact force (mN)        median  1550.500000
5    II    impact force (mN)        median   573.000000
6   III    impact force (mN)        median   544.000000
7    IV    impact force (mN)        median   460.500000
8     I    impact force (mN)           std   630.207952
9    II    impact force (mN)           std   424.573256
10  III    impact force (mN)           std   124.273849
11   IV    impact force (mN)           std   234.864328
12    I    impact force (mN)  coeff_of_var     2.491165
13   II    impact force (mN)  coeff_of_var     1.709306
14  III    impact force (mN)  coeff_of_var     4.541508
15   IV    impact force (mN)  coeff_of_var     1.830791
16    I  adhesive force (mN)          mean  -658.400000
17   II  adhesive force (mN)          mean  -462.300000
18  III  adhesive force (mN)          mean  -206.750000
19   IV  adhesive force (mN)          mean  -263.600000
20    I  adhesive force (mN)        median  -664.500000
21   II  adhesive force (mN)        median  -517.000000
22  III  adhesive force (mN)        median  -201.500000
23   IV  adhesive force (mN)        median  -233.500000
24    I  adhesive force (mN)           std   167.143619
25   II  adhesive force (mN)           std   203.811600
26  III  adhesive force (mN)           std    88.122448
27   IV  adhesive force (mN)           std    83.309442
28    I  adhesive force (mN)  coeff_of_var    -4.041459
29   II  adhesive force (mN)  coeff_of_var    -2.327197
30  III  adhesive force (mN)  coeff_of_var    -2.407117
31   IV  adhesive force (mN)  coeff_of_var    -3.246305

In [18]:
df_frog = pd.DataFrame(
    data={
        "ID": ["I", "II", "III", "IV"],
        "age": ["adult", "adult", "juvenile", "juvenile"],
        "SVL (mm)": [63, 70, 28, 31],
        "weight (g)": [63.1, 72.7, 12.7, 12.7],
        "species": ["cross", "cross", "cranwelli", "cranwelli"],
    }
)

In [19]:
df_frog

    ID       age  SVL (mm)  weight (g)    species
0    I     adult        63        63.1      cross
1   II     adult        70        72.7      cross
2  III  juvenile        28        12.7  cranwelli
3   IV  juvenile        31        12.7  cranwelli

In [20]:
df

,date,ID,trial number,impact force (mN),impact time (ms),impact force / body weight,adhesive force (mN),time frog pulls on target (ms),adhesive force / body weight,adhesive impulse (N-s),total contact area (mm2),contact area without mucus (mm2),contact area with mucus / contact area without mucus,contact pressure (Pa),adhesive strength (Pa)
0,2013_02_26,I,3,1205,46,1.95,-785,884,1.27,-0.290,387,70,0.82,3117,-2030
1,2013_02_26,I,4,2527,44,4.08,-983,248,1.59,-0.181,101,94,0.07,24923,-9695
2,2013_03_01,I,1,1745,34,2.82,-850,211,1.37,-0.157,83,79,0.05,21020,-10239
3,2013_03_01,I,2,1556,41,2.51,-455,1025,0.74,-0.170,330,158,0.52,4718,-1381
4,2013_03_01,I,3,493,36,0.80,-974,499,1.57,-0.423,245,216,0.12,2012,-3975
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2013_06_18,IV,4,402,38,3.00,-302,986,2.25,-0.122,117,30,0.07,3446,-2591
76,2013_06_21,IV,1,605,39,4.50,-216,1627,1.61,-0.139,123,20,1.00,4928,-1759
77,2013_06_21,IV,2,711,76,5.30,-163,2021,1.21,-0.217,129,42,0.97,5498,-1257
78,2013_06_21,IV,3,614,33,4.57,-367,1366,2.73,-0.198,128,108,0.46,4776,-2857
79,2013_06_21,IV,4,468,36,3.48,-218,1269,1.63,-0.122,129,68,0.61,3617,-1688

In [22]:
pd.merge(left=df, right=df_frog, how='left', left_on=['ID'], right_on=['ID'])
#better way -> df.merge(df_frog, on='ID')

,date,ID,trial number,impact force (mN),impact time (ms),impact force / body weight,adhesive force (mN),time frog pulls on target (ms),adhesive force / body weight,adhesive impulse (N-s),total contact area (mm2),contact area without mucus (mm2),contact area with mucus / contact area without mucus,contact pressure (Pa),adhesive strength (Pa),age,SVL (mm),weight (g),species
0,2013_02_26,I,3,1205,46,1.95,-785,884,1.27,-0.290,387,70,0.82,3117,-2030,adult,63,63.1,cross
1,2013_02_26,I,4,2527,44,4.08,-983,248,1.59,-0.181,101,94,0.07,24923,-9695,adult,63,63.1,cross
2,2013_03_01,I,1,1745,34,2.82,-850,211,1.37,-0.157,83,79,0.05,21020,-10239,adult,63,63.1,cross
3,2013_03_01,I,2,1556,41,2.51,-455,1025,0.74,-0.170,330,158,0.52,4718,-1381,adult,63,63.1,cross
4,2013_03_01,I,3,493,36,0.80,-974,499,1.57,-0.423,245,216,0.12,2012,-3975,adult,63,63.1,cross
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,2013_06_18,IV,4,402,38,3.00,-302,986,2.25,-0.122,117,30,0.07,3446,-2591,juvenile,31,12.7,cranwelli
76,2013_06_21,IV,1,605,39,4.50,-216,1627,1.61,-0.139,123,20,1.00,4928,-1759,juvenile,31,12.7,cranwelli
77,2013_06_21,IV,2,711,76,5.30,-163,2021,1.21,-0.217,129,42,0.97,5498,-1257,juvenile,31,12.7,cranwelli
78,2013_06_21,IV,3,614,33,4.57,-367,1366,2.73,-0.198,128,108,0.46,4776,-2857,juvenile,31,12.7,cranwelli
79,2013_06_21,IV,4,468,36,3.48,-218,1269,1.63,-0.122,129,68,0.61,3617,-1688,juvenile,31,12.7,cranwelli